use customer_shopping_behaviour

select TOP 20 * from customer_shopping

-- What is the total Revenue generated by male and female customers
select gender, sum(purchase_amount) as total_revenue from customer_shopping
Group By gender

-- which customer used discount but still spent more than average purchase amount
select customer_id, discount_applied, purchase_amount from customer_shopping
where discount_applied = 'yes' and purchase_amount > 
(
  select AVG(purchase_amount) from customer_shopping
)

-- which are the top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating),2) as avgrating from customer_shopping
group by item_purchased
order by avgrating desc

-- compare the average purchase amounts between standard and express shipping
select avg(purchase_amount) as avgamount, shipping_type from customer_shopping
where shipping_type in('Express','Standard')
Group By shipping_type

-- Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers
select subscription_status, count(customer_id) as total_customers,avg(purchase_amount) as avgamount, sum(purchase_amount) as total_revenue from customer_shopping
Group By subscription_status

-- which 5 products have the highest percentage of purchases with discount applied
select TOP 5 item_purchased, round(count(case when discount_applied = 'Yes' then 1 end)*100/count(*),2) as discount_purchase from customer_shopping
Group BY item_purchased
order by discount_purchase desc


--Segment customers in to new, returning and loyal based on their total number of previous purchases and show the count of each segment
--select 
--case 
--    when previous_purchases = 1 then 'new'
--    when previous_purchases < 50 then 'returning'
--    else 'loyal'
--    end as customer_segment,
--    count(*) as count_segment
--from customer_shopping
--group by 
--      case 
--    when previous_purchases = 1 then 'new'
--    when previous_purchases < 50 then 'returning'
--    else 'loyal'
--    end;

WITH customer_type AS (
    SELECT 
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases between 2 and 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer_shopping
)
SELECT 
    customer_segment,
    COUNT(*) AS count_segment
FROM customer_type
GROUP BY customer_segment;

-- what are the top 3 most purchased products with in each category

WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,

        -- count how many times each product was purchased
        COUNT(*) AS total_purchases,

        -- rank products separately inside every category
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn

    FROM customer_shopping

    -- Make one row for each product inside each category
    GROUP BY category, item_purchased
)

-- Keep only rank 1, 2, and 3
SELECT 
    category,
    item_purchased,
    total_purchases
FROM ranked_products
WHERE rn <= 3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select count(customer_id) as previous_customers , subscription_status from customer_shopping
where previous_purchases >5 
Group by subscription_status

-- what is the revenue contribution of each group
select age_group, sum(purchase_amount) as total_amount
from customer_shopping
group by age_group
order by total_amount desc